### ISSUE TITLE
How to store/retrieve puzzles?

### ISSUE THREAD

**Issue by JoseGeorges8** [AlvinRamoutar/sudoku-api#1]
Hi, 

I've been working on a simple sudoku app from a couple weeks now and I thank you for this api! it's been really useful and it seems to work flawless!

one think that I haven't been able to figure out is how would you reopen an already started puzzled (The user left the app and wants to continue later)? is that something that can be done with the current state of your api?

Thanks in advance, overall this is great!

**Comment by AlvinRamoutar** [comment]
Hey @JoseGeorges8 !

Being able to save and load a puzzle is something I'm working on!
As of now, I'm looking into serialization of PuzzleOptions (which contains metadata about Sudoku puzzles), along with the puzzles themselves - both the solved grid and active grid.

Is there a specific way you'd like to load/save puzzles?
What file formats would you prefer to see saves in?

Glad to hear you're having fun with it.
Cheers!

**Comment by JoseGeorges8** [comment]
Thanks for the quick reply Alvin! Well I think if it can be serialized to json it'll be great, simply making it a Map<String, dynamic> is what I think is pretty standard and flexible.

If you're accepting contribution and want some help I can definitely contribute too!

**Comment by AlvinRamoutar** [comment]
Perfect; was going for something similar.
Contributions are always welcome; go ahead and make a PR.
Cheers!

**Comment by JoseGeorges8** [comment]
Hey Alvin!

So I was able to create serialization, only problem is I can't push to your repo to create the PR.

Couple things I wanted to mention:

1. Due to the way I went for doing serialization, I had to remove the `ICell` interface off the cell class, since it wouldn't let me create a private constructor. I wanted you to review the code and see if we can find a better approach for that use case.
2. I found weird behaviour with the `isPrefill` property from the `Cell`. It seems that on puzzle generation this property stays null and therefore adding it to my `toMap` method breaks the unit test. 

I think those two points are easier to look through the PR, but overall it worked fine and I'm able to save puzzles on a Json file and retrieve them properly!

Let me know if I can get access to push my branch and create a PR 👍

**Comment by AlvinRamoutar** [comment]
Hey @JoseGeorges8 ,

Alright, let's see...

1. The reason I've created an `ICell` was for future implementations of [**markup**](http://pi.math.cornell.edu/~mec/Summer2009/meerkamp/Site/Solving_any_Sudoku_II.html). For more difficult puzzles, this will serve very useful. However, I'm still debating as to whether or not it's even _in_ the scope of this API (since it's less about the puzzle, and more of a strategy to solving puzzles).
2. I'll have to take a look into that. `isPrefill` is a useful piece of logic when building puzzle UIs, since you might want to make cells that are prefilled to be read-only. **Could you please create a new issue for this?**

As for contributing, [I hope this helps you make a Pull Request.](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request)
I'm guessing the issue you're having is that you've created a new branch - **please fork and create a PR against `dev`** (I'll update the readme to state this).

Let me know if there's any more questions, cheers!

**Comment by JoseGeorges8** [comment]
I see, I'd love to see more difficult and a wider variety of patterns too since I'm using the api to create a sudoku game, regardless I'll create the PR and create the issue about the `isPrefill`

cheers!

**Comment by AlvinRamoutar** [comment]
Hey @JoseGeorges8 ,

I've merged #4 , and will be closing this issue.
**Thank you for your contribution in #4 !** 🎉 

If you want, you're free to open a new issue for additional patterns.

Cheers,
Alvin

**Comment by zs-adarsh** [comment]
Hey, first of all thanks for this awesome package!
I was trying to store my puzzles in Hive using puzzle.topMap();
But i am getting the following error:
Unhandled Exception: HiveError: Cannot write, unknown type: _HashSet<int>. Did you forget to register an adapter?

Any idea why this could be happening?
Thanks in advance!

**Comment by AlvinRamoutar** [comment]
Hey @zs-adarsh ,
I'll have to try that out, can you please open a new issue for this?
Thank you!

**Comment by zs-adarsh** [comment]
Hey!
I just opened a new issue for the same. Do check at #12.
