### ISSUE TITLE
isPrefill marked as null after generating a puzzle

### ISSUE THREAD

**Issue by JoseGeorges8** [AlvinRamoutar/sudoku-api#2]
Quickest steps to reproduce:

1. Create a new puzzle as stated in the example
2. generate puzzle
3. loop through the cells inside each row in the grid and called their `prefill()` getter. This will return null

**Comment by AlvinRamoutar** [comment]
The `prefill` property of a `Cell` was not kept when performing `Grid.deepClone()`.

This has been fixed by adding:
`_target.matrix()[r][c].setPrefill(source.matrix()[r][c].prefill());`
To:
`Grid.deepClone(Grid source)`

I've also added a test to `generation_test` specifically for prefill validity.

Let me know if this resolves your issue @JoseGeorges8 .

**Comment by AlvinRamoutar** [comment]
If you can confirm this resolution, then I'll close this issue, proceed with merging the fix into `dev`, and ask you to adjust PR #4.

**Comment by JoseGeorges8** [comment]
Just checked it out and can confirm that fixes the issue 👍

**Comment by AlvinRamoutar** [comment]
Thanks @JoseGeorges8 , closing and completing merge.
